# -*- coding: utf-8 -*-
"""week08_01_problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TKaoghYXfDU0Jrom51lUk0Svq80LpDp6
"""

import numpy as np


class CoordArray:
    def __init__(self, N):
        np.random.seed(0)
        self.n = N
        # from -10 to 10 random integer, N x 2 array
        self.array = np.random.randint(-10, 11, (N, 2))
        self.col_avg = None
        self.row_avg = None

    def mean(self, axis):
        # 각 행별 평균, 열별 평균을 구하는 함수
        if axis == 0:
            self.col_avg = np.mean(self.array, axis=0)
            return self.col_avg
        elif axis == 1:
            self.row_avg = np.mean(self.array, axis=1)
            return self.row_avg
        else:
            return None

    def sort(self):
        # 원점(0,0)과의 거리를 기준으로 좌표행렬을 내림차순 정렬하는 함수
        distances = np.linalg.norm(self.array, axis=1)
        sorted_indices = np.argsort(distances)[::-1]  # Sort indices in descending order
        self.array = self.array[sorted_indices]

    def distance(self, x:int, y:int):
        # 새로운 좌표 x, y를 입력받으면 좌표 행렬에서 각 좌표와 거리를 구하고, 
        # 가장 먼 좌표와의 거리를 반환하는 함수
        point = np.array([x, y])
        distances = np.linalg.norm(self.array - point, axis=1)
        max_distance = np.max(distances)
        return round(max_distance, 2)


#### Do not edit here ####
# All the test should print True
CA5 = CoordArray(5)
CA10 = CoordArray(10)
CA5.mean(0)
CA5.mean(1)
CA10.mean(0)
CA10.mean(1)

print(CA5.col_avg[0]==-1.6)
print(CA5.col_avg[1]==-0.4)
print(CA5.row_avg[2]==-5.)
print(CA5.row_avg[3]==4.)
print(CA10.col_avg[0]==-1.4)
print(CA10.col_avg[1]==-0.7)
print(CA10.row_avg[2]== -5.)
print(CA10.row_avg[3]== 4.)

CA5.sort()
CA10.sort()

CA5.mean(0)
CA5.mean(1)
CA10.mean(0)
CA10.mean(1)

print(CA5.row_avg[2]==4.)
print(CA5.row_avg[3]==-5.)
print(CA10.row_avg[2]== -6.5)
print(CA10.row_avg[3]== 4.)
print(CA5.array[4][1]==5)
print(CA10.array[8][0]==-4)

coord, dis = CA5.distance(5, 3)
print(np.all([coord,(-10, -7)], where=[[True, True]]))
print(dis==18.03)
coord, dis = CA10.distance(9,-2)
print(np.all([coord,(-10, -7)], where=[[True, True]]))
print(dis==19.65)