# -*- coding: utf-8 -*-
"""week09_02_problem.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18E1Lx6O7Rn0XPYtGNMFYfpX_fJRmsjCw
"""

# 라이브러리 import
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Machine-Learning에 필요한 라이브러리 import
import sklearn
from sklearn.model_selection import train_test_split

# 데이터 불러오기
titanic_df= pd.read_csv('titanic.csv')

# data 10개 출력  
print(titanic_df.head(10))